### ISSUE TITLE
Help required using Aubio in Swift iOS project

### ISSUE THREAD

**Issue by rkgi10** [aubio/aubio#34]
Hi,
I'm new to both iOS(swift) and to aubio. I just want to implement a simple functionality of pitch detection in my app, by passing an audio file to aubio, and have it return the pitch value in Hz with timestamp. While I've been able to do this with the command line using 'aubiopitch', I've no idea how to do it in iOS(swift). Right now I've included the aubio framework inside my app and included the Accelerate framework, and created a bridging header to include the header files.
Can somebody please help me out with a basic implementation of the above said functionality?

**Comment by piem** [comment]
hi @rkgi10,

I'm not familiar with Swift yet, but you should be able to use the C functions directly from it.

Creating a [module map](http://spin.atomicobject.com/2015/02/23/c-libraries-swift/) seems to be most of what it takes.

**Comment by piem** [comment]
Please try the following: download and install the [following framework](https://aubio.org/bin/tmp/aubio-0.4.3~const.iosuniversal_framework.zip) to your project, also adding ``Accelerate.framework``.

The following Swift code example should work fine:

```swift
import aubio

let a = new_fvec(512)
fvec_ones(a)
fvec_print(a)
var method = "default"
let b = new_aubio_tempo(method, 512, 256, 44100)
let c = new_aubio_pitch("default", 512, 256, 32000)
        
aubio_tempo_get_bpm(b)
del_aubio_tempo(b)
del_aubio_pitch(c)
del_fvec(a)
```

Let us know how it goes!

**Comment by rjcristy** [comment]
Hi!, I'm sorry but this is really new to me

    Cannot convert value of type 'String' to expected argument type 'UnsafeMutablePointer<char_t>' (aka 'UnsafeMutablePointer<Int8>')

2 same errors goes at 

    let b = new_aubio_tempo(method, 512, 256, 44100)
    let c = new_aubio_pitch("default", 512, 256, 32000)

Hope you can help me understand the situation. Thank you

**Comment by piem** [comment]
did you update to the framework linked above? it should fix this error.

**Comment by piem** [comment]
hi @rkgi10 and @rjcristy, did you get any chance trying the zip file linked above?

**Comment by piem** [comment]
Ok, so aubio functions should really be using 'const char *' instead of 'char *'.

In the mean time, you can use this to pass a String to the C functions:

```swift
let path : String = "/path/to/soundfile.wav"
let t = path.withCString { cstr in 
    new_aubio_source(UnsafeMutablePointer(cstr), 44100, 512)
}
/// do stuff with t, and later delete it
del_aubio_tempo(t)
```

Let me know how it goes.

**Comment by rkgi10** [comment]
Hi @piem ,
The code that you gave above runs fine with the updated framework. Thanks for that. But when I try to initialise a new aubio source, using the technique that you showed(using .withCString), it gives an error. The error is Undefined symbols for architecture arm64:
  "_ExtAudioFileSeek". Xcode shows 7 of these errors(as they have been referenced in your framework 7 times). Please look into this.
 Also I wanted to ask, is there any way to get the output of function aubio_pitch_do in a .csv file ?

**Comment by piem** [comment]
@rkgi10 Hi @rkgi10, you need to add the AudioToolbox framework too.

**Comment by piem** [comment]
for the csv output (that should go in a new issue), you can use the aubiopitch program:

    $ aubiopitch -i soundfile.wav | sed 's/ /,/' > soundfile.csv

**Comment by Greg767** [comment]
@rkgi10 What kind of input data did you use for this? The exemple is not clear for me where the data is and how to feed a buffer into it. Thank you.

**Comment by dantarakan** [comment]
Hi @piem , sorry for digging up the old thread. I am attempting to use the updated framework, however I'm having an issue when Bitcode is enabled in my build settings. This is the same issue as was referenced in #31 .

I rebuilt the binary with CFLAGS="-fembed-bitcode", however I'm not sure how to convert it into a framework, as I'm very new to iOS. Could you please update the framework, or point me in the right direction?

Thank you in advance!

**Comment by piem** [comment]
hi @dantarakan 

i just pushed the script i use to build ios and osx frameworks. you should be able to run with:

    $ ./scripts/build_apple_frameworks

left to do is updating the `char_t *` with `const`.

**Comment by dantarakan** [comment]
Hi @piem ,
Thank you very much! I am now able to use Aubio in my project.

Although, here are a couple minor issues with the script:
1. It doesn't work if one of the top-level folders contains a space.
2. The "apple/Modules" folder within the "scripts" folder is not created by the scripts, so needed to be created manually.
3. It doesn't create a module map within the framework.

That being said, these issues are just nice-to-have. Again, thanks for your work!

**Comment by piem** [comment]
@dantarakan  oops, i forgot to add those two files, thanks for the reminder! :)

**Comment by dantarakan** [comment]
@piem , I've got another issue now.
I'm trying to use the resampler, however I'm getting the following error:

> aubio was not compiled with libsamplerate

Is there a way to pass options to your new script? 
I've tried tweaking Line 243 in wscript to the following:
`if (ctx.options.enable_samplerate == False):`

But I still get the same error.

Thanks!

**Comment by piem** [comment]
@dantarakan please open a new issue for this, thanks!

**Comment by piem** [comment]
Hi all!

`const` qualifiers were added in the latest commits, so that the following code should now work out of the box in Swift, after rebuilding the latest framework from the `develop` branch.

```swift
        let samples = new_fvec(512)
        let source = new_aubio_source( "/tmp/4bus.wav", 0, 512)
        let samplerate = aubio_source_get_samplerate(source)
        let tempo = new_aubio_tempo("default", 512, 256, samplerate)
        let pitch = new_aubio_pitch("default", 512, 256, samplerate)
        let out = new_fvec(2)
        var read : uint_t = 0
        var total_frames : uint_t = 0
        while true {
            aubio_source_do(source, samples, &read )
            aubio_tempo_do(tempo, samples, out)
            if (fvec_get_sample(out, 0) != 0) {
                let beat_time : Float = Float(total_frames) / Float(samplerate)
                puts( String(format: "beat at %.2f", beat_time))
            }
            aubio_pitch_do(pitch, samples, out)
            if (aubio_pitch_get_confidence(pitch) > 0.7) {
                puts( String(format: "pitch at %.2f", fvec_get_sample(out, 0)))
            }
            total_frames += read
            if (read < 512) {
                break
            }
        }
        del_fvec(out)
        del_aubio_pitch(pitch)
        del_aubio_tempo(tempo)
        del_aubio_source(source)
        del_fvec(samples)
        puts( String(format: "read %d total frames", total_frames) )
```

Let us know if it helps!

Best, Paul

**Comment by xjefftang** [comment]
Hi Paul,
I happen to be looking for some Swift example code to get beats for recorded audio, and you latest code helps a lot! Maybe this is an aubio question - I'm not sure I understand the output beat and pitch values:

pitch at 2867.43
beat at 3.39
beat at 3.84
beat at 4.30
pitch at 0.00
beat at 4.75
pitch at 0.00
pitch at 2678.77
beat at 5.20
beat at 5.65
pitch at 2725.72
pitch at 2659.89
beat at 6.07
beat at 6.57
beat at 7.08
beat at 7.58
pitch at 0.00
pitch at 0.00
pitch at 0.00
beat at 8.09
pitch at 2678.54
pitch at 2647.63
beat at 8.59
pitch at 2782.43
pitch at 2741.21
pitch at 2775.33
pitch at 2797.89
beat at 10.26
pitch at 2766.85
pitch at 2771.19
pitch at 2777.87
pitch at 2833.39
pitch at 2815.76
pitch at 2749.41
beat at 11.81
pitch at 2514.83
pitch at 3711.17
read 551997 total frames

The recorded wav file is attached as a zip file. Could you please explain what those pitch/beat values mean? Does it make sense for the audio wav file? It's a 12-second audio file, and there're 14 beats..

Thanks a lot,
Jeff

[21042016-224437.wav.zip](https://github.com/aubio/aubio/files/231203/21042016-224437.wav.zip)

**Comment by piem** [comment]
Hi @xjefftang 

beat positions are in seconds, pitch values are in Hz. pitch are only displayed when found with a confidence above 0.7.

best, Paul

**Comment by xjefftang** [comment]
Thanks Paul. I noticed the beats output from the Swift code above and using the aubiotrack (with the default settings) on the same audio file are different. Why so and can we make them the same, or which one is more accurate?

I built aubiotrack (and other aubio* commands) using https://github.com/aubio/aubio and 
```
./waf configure
./waf build
sudo ./waf install
```

Best,
Jeff

**Comment by piem** [comment]
@xjefftang, the buffer_size and hop_size for the tempo object were wrong in the code above.

changed them to 1024/512 now, in line with the source's hop_size. it should help.

best, Paul

**Comment by xjefftang** [comment]
Hi Paul, cool the updated code (which has been edited into the code above, for others' info) outputs the exactly same results as the aubiotrack program.

**Comment by piem** [comment]
Hi Jeff,

The tempo algorithm needs a few seconds of audio to estimate the beat, so most often it doesn't get the first ones in a file.

Best, Paul

**Comment by xjefftang** [comment]
Hi Paul,

Thanks for the info. Another question please: should the difference between any two consecutive beats be all the same? The aubiotrack doc (http://aubio.org/manpages/latest/aubiotrack.1.html) says that "aubiotrack attempts to detect beats, the time where one would intuitively be tapping his foot." Should one tap beats at the same fixed time interval?

Thanks and best,
Jeff

**Comment by xjefftang** [comment]
Hi Paul,

Could you also please clarify if the aubio library can be used to do tempo (beats per minute) recognition? If so, which command is it and how can I get the BPM with it?

Thanks for all your help!
Jeff

**Comment by piem** [comment]
Hi @xjefftang 

Please open a new issue that include your last two questions!

Many thanks, Paul

**Comment by xjefftang** [comment]
Hi Paul, sorry - yes this is a Swift issue :) Will do it right away.
Best,
Jeff

**Comment by xjefftang** [comment]
Hi Paul,

Could you please offer an example of getting notes in Swift, generating the same result as the aubionotes program? I tried to port the aubionotes.c code to Swift, but am still getting some errors.

This is a sample result of using aubionotes:
aubionotes 5.m4a 
72.000000	0.690794	1.532517
76.000000	1.532517	2.362630
79.000000	2.362630	3.169524
76.000000	3.169524	4.028662
72.000000	4.028662	4.870386
102.000000	4.870386	4.922630
67.000000	4.922630	4.986485

Thanks!
Jeff

**Comment by xjefftang** [comment]
Hi Paul,

I'm still trying to port the aubionotes.c to Swift so I can get what the aubionotes program returns in iOS. Then I noticed note seems to be obtained from onset and pitch, so I thought I should try first to port aubioonset.c. Below is my Swift code, but when I run it on some sample sound, "beat at .." and "pitch t ..." look good, but "onset at ..." returns all 0's (same if I use different buffer_size in the new_aubio_onset call):
```
            let source = new_aubio_source(UnsafeMutablePointer(cstr), 0, 512)
            let samplerate = aubio_source_get_samplerate(source)
            let tempo = new_aubio_tempo("default", 1024, 512, samplerate)
            let pitch = new_aubio_pitch("default", 2048, 512, samplerate)
            let onset = new_aubio_onset ("default", 512, 512, samplerate)
            aubio_onset_set_threshold (onset, 0.3)
            aubio_onset_set_silence (onset, -90);
            let out_onset = new_fvec (1);
            let out = new_fvec(1)
            var read : uint_t = 0
            var total_frames : uint_t = 0
            while true {
                aubio_source_do(source, samples, &read )
                aubio_tempo_do(tempo, samples, out)
                if (fvec_get_sample(out, 0) != 0) {
                    let beat_time : Float = Float(total_frames) / Float(samplerate)
                    puts( String(format: "beat at %.4f", beat_time))
                    beatsSet?.addObject(Double(beat_time as NSNumber))
                }
                aubio_pitch_do(pitch, samples, out)
                if (aubio_pitch_get_confidence(pitch) > 0.7) {
                    puts( String(format: "pitch at %.2f", fvec_get_sample(out, 0)))
                }
                
                aubio_onset_do(onset, samples, out_onset)
                puts( String(format: "onset at %.2f", fvec_get_sample(out_onset, 0)))
                
                total_frames += read
                if (read < 512) {
                    break
                }
            }
            del_fvec(out)
            //del_aubio_pitch(pitch)
            del_aubio_onset(onset)
            del_aubio_tempo(tempo)
            del_aubio_source(source)
            del_fvec(samples)

```

What did I do wrong? Also, if I can get correct onset values, do I also need to get pitches then calculate the notes based on those two sets of values?

I've been stuck on this for a while.. Thanks for your help!

Best,
Jeff

**Comment by xjefftang** [comment]
I figured it out - using code below works!
```
aubio_onset_do(onset, samples, out_onset)
                
                if (fvec_get_sample(out_onset, 0) != 0) {
                    puts(String(format: ">>> %.2f", aubio_onset_get_last_s(onset)))
                }
```

Best, 
Jeff

**Comment by andresinaka** [comment]
hi guys, Does anybody have a working sample project to share???

**Comment by piem** [comment]
hi @andresinaka ,

I have a simple project I use to test the framework. It needs to be cleaned-up a bit, but if it helps I will find the time make a little repo for it.

best, paul

**Comment by andresinaka** [comment]
@piem thanks dude! that would be great!

**Comment by DesperadoFlames** [comment]
Hi @piem  ,
I'm have a Swift project and I want to use aubio to detect the beats, but I got stuck when reading the source file. 

My code looks like this:
`let path : String = "Music.mp3"
        let t = path.withCString { cstr in
            new_aubio_source(UnsafeMutablePointer(cstr), 44100, 512)
        }`

And I always get the errors below:
AUBIO ERROR: source_apple_audio: Failed opening Music.mp3, error in ExtAudioFileOpenURL ('wht?')
AUBIO ERROR: source_wavread: Failed opening Music.mp3 (System error: No such file or directory)
AUBIO ERROR: source: failed creating aubio source with Music.mp3 at samplerate 44100 with hop_size 512

I don't know why this happened because I followed the code you gave above. 

Thanks a lot!!

**Comment by laurentVeliscek** [comment]
Hi Piem,

Aubio looks just amazing and powerful. Thanks for sharing !

I could run your swift example code in an XCode project using 0.4.3 compiled framework from this thread.
It seems to work fine with simulator but I had to disable bitcode to make it run on my iphone 4S.

I failed to recompile IOS framework from source. 
:-/
Is there an updated "bitcode" compliant IOS framework that can be downloaded ?

Thanks a lot,

Laurent.

**Comment by piem** [comment]
Hi,

@DesperadoFlames, what if you use something along this line:

```swift
            let source = new_aubio_source(UnsafeMutablePointer(cstr), 0, 512)
```

The error message you are getting seems to indicate CoreAudio ExtAudioFileRef could not find out how to decode that file (wht?).

@laurentVeliscek , please see the script `build_apple_frameworks` to find out how to rebuild the frameworks for macos and ios. On ios, the option `-fembed-bitcode` is used by default. Any idea why you had to turn it off?

Best, Piem

**Comment by piem** [comment]
aubio in swift seems to work as expected now. please re-open this issue if needed.

best, piem
